### ISSUE TITLE
Provide CLI based help info

### ISSUE THREAD

**Issue by gaudeon** [curtjen/server-mount#1]
Example:
> ssm help
Usage: ssm [options]

This is a CLI tool for mounting remote directories to your local machine. 

    config - ssm will use the supplied json file for it's configuration

    help - prints this help information

    unmount - If no config is defined, unmount using sm-config.json in same directory you're running the command in. If config is defined, unmount using supplied config.

**Comment by curtjen** [comment]
For some reason, having a help command slipped my mind. I've gone ahead and added it to my roadmap/todo: [https://github.com/curtjen/server-mount/wiki/Roadmap](https://github.com/curtjen/server-mount/wiki/Roadmap)

Thanks 👍
